image: microsoft/dotnet:2.1-sdk

variables:
  VERSION: "3.1.1"

  ASP_PROJECT_PATH: "src/$ASP_PROJECT_NAME"
  TEST_ASP_PROJECT_PATH: "src/$ASP_PROJECT_NAME.Tests"

  NUGET_PACKAGES: /storage/nuget

build_project:
  stage: build
  script:
    - dotnet restore --packages /storage/nuget
    - dotnet build -c Release --no-restore $ASP_PROJECT_PATH
  except:
    - tags
  artifacts:
    untracked: true
    expire_in: 1 day

test_image:
  stage: test
  script:
    - dotnet restore --packages /storage/nuget
    - dotnet test $TEST_ASP_PROJECT_PATH -c Release --no-restore
  except:
    - tags
  dependencies:
    - build_project

pack_image:
  stage: pack
  script:
    - dotnet restore --packages /storage/nuget
    - dotnet pack -c Release --no-restore $ASP_PROJECT_PATH --include-symbols --include-source
  only:
    - master
  dependencies:
    - build_project
  artifacts:
    untracked: true
    expire_in: 1 day

pack_image_dev:
  stage: pack
  script:
    - dotnet restore --packages /storage/nuget
    - dotnet pack -c Release --no-restore --version-suffix "build-$CI_JOB_ID" $ASP_PROJECT_PATH
  only:
    - develop
  dependencies:
    - build_project
  artifacts:
    untracked: true
    expire_in: 1 day

publish_image:
  stage: publish
  script:
    - dotnet nuget push $ASP_PROJECT_PATH/bin/Release/*.nupkg -s $NUGET_URI -k $NUGET_USER:$NUGET_PASSWORD
  only:
    - master
  dependencies:
    - pack_image

publish_image_dev:
  stage: publish
  script:
    - dotnet nuget push $ASP_PROJECT_PATH/bin/Release/*.nupkg -s $NUGET_URI -k $NUGET_USER:$NUGET_PASSWORD
  only:
    - develop
  dependencies:
    - pack_image_dev

stages:
  - build
  - test
  - pack
  - publish
